name: Pre-commit auto-update

on:
  # every first day of the month
  schedule:
    - cron: "0 0 1 * *"
  # on demand
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update:
    uses: mathbunnyru/pre-commit-workflows/.github/workflows/pre-commit-autoupdate.yml@main
